name: django-project-DRF


services:
  main:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - django_static:/usr/src/app/static

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    build:
      context: ./nginx
    volumes:
      - django_static:/home/app/main/static
    ports:
      - '80:80'
    depends_on:
      - main


volumes:
  psql_data:
  django_static:
